import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

export const metadata: Metadata = {
 title: 'Rizki & Dinda',
 description: 'Generated by create next app',
};

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
  <html lang="en">
   <body className={`scrollbar-none`}>{children}</body>
  </html>
 );
}
